hardware:
  # Add hardware devices here [status, address]
  # Motor Controller
  mot: [true, 8]

  # Power Safety
  psa: [false, 9]

  # Arm Controller
  arm: [false, 10]
  
  # Torpedo Controller
  tor: [false, 11]

  # IMU
  imu: [false, 12]

  # Display
  dis: [false, 13]
