line-length = 100
target-version = "py310"

[lint]
select = [
  "E","F",        # pycodestyle/pyflakes
  "I",            # import sorting
  "B",            # flake8-bugbear
  "UP",           # pyupgrade
  "N",            # pep8-naming
  "A",            # flake8-builtins
  "COM",          # commas
  "C4",           # comprehensions
  "ICN",          # import conventions
  "PIE",          # misc lints
  "PT",           # pytest style
  "RET",          # return
  "SIM",          # simplify
  "RUF",          # ruff-specific
]
ignore = [
  "E501",   # let black handle line length
]
fixable = ["ALL"]

[lint.isort]
known-first-party = ["libs"]
combine-as-imports = true
